### ISSUE TITLE
modify parameters in-place in sciml_train!

### ISSUE THREAD

**Issue by ric-cioffi** [JuliaDiffEq/DiffEqFlux.jl#140]
This is more of a suggestion rather than an issue.
I'd find it much more intuitive to have `sciml_train!` to modify the parameters in-place, which would be consistent with `Flux.train!`'s behavior.

**Comment by ChrisRackauckas** [comment]
I am going the complete other direction in https://github.com/JuliaDiffEq/DiffEqFlux.jl/pull/139 and just renaming it `sciml_train` instead of `sciml_train!`. One of the purposes of this was to get rid of the global behavior because it's brittle, not thread-safe, and can lead to some weird performance issues.

**Comment by ric-cioffi** [comment]
I'm totally fine with this as well, but it should probably be highlighted in the docs that `DiffEqFlux.sciml_train` behaves differently from `Flux.train!` even when called with a `Flux` optimizer.

**Comment by ChrisRackauckas** [comment]
Yes, it does behave differently from Flux.train! in more than one way, another being after https://github.com/JuliaDiffEq/DiffEqFlux.jl/pull/139 the boolean in the callback. Another is the `maxiters` stuff. So I think we just break the link and don't look back. People can still use Flux.train! if they want, but we can just give an interface that's better for the kinds of applications we see.

**Comment by ChrisRackauckas** [comment]
Went the route of #139
