### ISSUE TITLE
Setup progress bar of sciml_train to be platform agnostic

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqFlux.jl#158]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/10efbd7e331f181379118d9e8e4b6a4c5e2216b8/src/solve.jl#L89

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/311726795dabdabe50a8392d753213b6d5d74c2e/src/integrators/integrator_utils.jl#L132-L136

is how it should be done. Then it should auto-switch over to command line tools. @tkf are the command line tools done?

**Comment by tkf** [comment]
Do you mean a terminal-based progress bar UI? There is https://github.com/c42f/TerminalLoggers.jl so it should work now. A toy example:

```julia
using Logging
using OrdinaryDiffEq
using TerminalLoggers

with_logger(TerminalLogger()) do
    solve(
        ODEProblem((u, p, t) -> (sleep(0.01); -u), 1.0, nothing),
        Euler();
        dt = 0.5,
        tspan = (0.0, 100.0),
        progress = true,
        progress_steps = 1,
    )
end
```

FYI, _ideally_,

* It'd be better to generate a UUID when creating a solver and store it to (e.g.) `integrator.progress_id`.  Then, you can pass it to the `_id` argument of `@logmsg`.  This matters only if you want to solve a diffeq inside another difffeq, though.
* Use `try`-`finally` in `solve` etc. to make sure you do `@logmsg` with `"done"`. Otherwise, progress bar UI can't tell the difference between very slow integration/training and crashed integration/training.  The next version of ProgressLogging.jl (a Juno.jl spin-off) is going to have [`ProgressLogging.@withprogress`](https://junolab.org/ProgressLogging.jl/dev/#ProgressLogging.@withprogress-Tuple) etc. that helps to do this.

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 @abhigupta768 reopening to make this just a little more automatic, following @devmotion's lead:

https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/454
