### ISSUE TITLE
Type issues when training weights are matrices

### ISSUE THREAD

**Issue by ianwilliamson** [JuliaDiffEq/DiffEqFlux.jl#18]
First of all, thanks for publishing this very interesting package!

I am trying to use this to do some backprop through an ODE where my parameters are matrices rather than a collection of scalars, as in the example. I am having trouble wrangling the type system into getting this to work.

If I try the approach given by the code below
```
p = [a, b]
prob = ODEProblem(deriv, u0, (0.0, T), p)
# sol  = solve(prob, SSPRK83(), dt=dt, progress=true, abstol=1e-6, reltol=1e-6, progress_steps=100);
params = Flux.Params([param(a), param(b)]);

function predict_rd()
  Array(diffeq_rd(param([a, b]), prob, SSPRK83(), dt=dt, progress=true, abstol=1e-6, reltol=1e-6, progress_steps=100))
end

loss_rd() = 1/sum(abs2, x for x in predict_rd()[400, 70, 1, :])

cb =  display(loss_rd())
```

I get the error
```
ERROR: MethodError: no method matching zero(::Type{Array{Float64,2}})
Closest candidates are:
  zero(::Type{LibGit2.GitHash}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LibGit2/src/oid.jl:220
  zero(::Type{Pkg.Resolve.VersionWeights.VersionWeight}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/resolve/VersionWeights.jl:19
  zero(::Type{Pkg.Resolve.MaxSum.FieldValues.FieldValue}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/resolve/FieldValues.jl:44
  ...
Stacktrace:
 [1] zero(::Array{Array{Float64,2},1}) at ./abstractarray.jl:849
 [2] TrackedArray(::Array{Array{Float64,2},1}) at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:32
 [3] param(::Array{Array{Float64,2},1}) at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/Tracker.jl:103
 [4] predict_rd() at ./none:2
 [5] loss_rd() at ./none:1
 [6] top-level scope at none:0
```

I think this must have something to do with my wrapping of `param()`.

**Comment by ianwilliamson** [comment]
Trying the following
```
function predict_rd()
  Array(diffeq_rd([param(a), param(b)], prob, SSPRK83(), dt=dt, progress=true, abstol=1e-6, reltol=1e-6, progress_steps=100))
end
```
gives
```
ERROR: MethodError: Cannot `convert` an object of type Float64 to an object of type TrackedArray{…,Array{Float64,2}}
Closest candidates are:
  convert(::Type{T<:TrackedArray}, ::S<:T<:TrackedArray) where {T<:TrackedArray, S<:T<:TrackedArray} at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:36
  convert(::Type{#s21} where #s21<:TrackedArray, ::TrackedArray) at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:38
  convert(::Type{#s21} where #s21<:TrackedArray{T,N,A}, ::AbstractArray) where {T, N, A} at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:41
  ...
Stacktrace:
 [1] _broadcast_getindex at ./broadcast.jl:578 [inlined]
 [2] getindex at ./broadcast.jl:511 [inlined]
 [3] copy at ./broadcast.jl:787 [inlined]
 [4] materialize at ./broadcast.jl:753 [inlined]
 [5] #diffeq_rd#1(::Array{Float64,3}, ::Base.Iterators.Pairs{Symbol,Real,NTuple{5,Symbol},NamedTuple{(:dt, :progress, :abstol, :reltol, :progress_steps),Tuple{Float64,Bool,Float64,Float64,Int64}}}, ::Function, ::Array{TrackedArray{…,Array{Float64,2}},1}, ::ODEProblem{Array{Float64,3},Tuple{Float64,Float64},true,Array{Array{Float64,2},1},ODEFunction{true,wave_equation,LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::SSPRK83{typeof(OrdinaryDiffEq.trivial_limiter!),typeof(OrdinaryDiffEq.trivial_limiter!)}) at /Users/iwill/.julia/packages/DiffEqFlux/1w1tX/src/Flux/layers.jl:8
 [6] (::getfield(DiffEqFlux, Symbol("#kw##diffeq_rd")))(::NamedTuple{(:dt, :progress, :abstol, :reltol, :progress_steps),Tuple{Float64,Bool,Float64,Float64,Int64}}, ::typeof(diffeq_rd), ::Array{TrackedArray{…,Array{Float64,2}},1}, ::ODEProblem{Array{Float64,3},Tuple{Float64,Float64},true,Array{Array{Float64,2},1},ODEFunction{true,wave_equation,LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem}, ::SSPRK83{typeof(OrdinaryDiffEq.trivial_limiter!),typeof(OrdinaryDiffEq.trivial_limiter!)}) at ./none:0
 [7] predict_rd() at ./none:2
 [8] loss_rd() at ./none:1
 [9] top-level scope at none:0
```

**Comment by ChrisRackauckas** [comment]
Flux internally makes the weights of its neural network be Float32 matrices. That's why when using neural_ode we set `u0` to be Float32. If you have all Float64 parameters, you should set `u0` to be Float64. Basically, you just want everything to match types. I'll need a working example if you'd like me to run it.

**Comment by ianwilliamson** [comment]
I thought my types were consistent, but I changed everything to Float32 just in case. It seems like this error is coming down the line 3 of `diffeq_rd()`:
```
_prob = remake(prob,u0=convert.(eltype(p),u0),p=p)
```
where it's trying to convert `u0`, which is now Float32 into the element type of `p` which is a `TrackedArray{…,Array{Float32,2}}`. The error thrown at the above line of `diffeq_rd()` is
```
ERROR: MethodError: Cannot `convert` an object of type Float32 to an object of type TrackedArray{…,Array{Float32,2}}
Closest candidates are:
  convert(::Type{T<:TrackedArray}, ::S<:T<:TrackedArray) where {T<:TrackedArray, S<:T<:TrackedArray} at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:36
  convert(::Type{#s21} where #s21<:TrackedArray, ::TrackedArray) at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:38
  convert(::Type{#s21} where #s21<:TrackedArray{T,N,A}, ::AbstractArray) where {T, N, A} at /Users/iwill/.julia/packages/Flux/GBuXv/src/tracker/lib/array.jl:41
```

I've assigned `p` as
```
a = ones(Float32, Nx, Ny)
b = ones(Float32, Nx, Ny)
p = [a, b]
```
and passed it to `diffeq_rd` as
```
diffeq_rd( param.(p), ...)
```
The difference from the example is that `a` and `b` are matrices rather than scalars, so you end up with an array of arrays situation, which is what is confusing `diffeq_rd` I think. Is this the correct way to pass them to `diffeq_rd`?

**Comment by ChrisRackauckas** [comment]
yeah, that should be using a recursive element type. Do you have an example code I can work with?

**Comment by ianwilliamson** [comment]
I just added you to the private repo that this code is in. Feel free to take a look at it whenever you get a chance. You can feel free to follow up via email, which is on my website linked in my profile

**Comment by wenquan** [comment]
We have encounted a similar problem here. We could sent you an example code as well. 
Thanks a lot!

**Comment by ChrisRackauckas** [comment]
Your example now works with DiffEqFlux.jl's current master, in a sense. If you make that `Array{TrackedArray}` a vector and just use views in your PDE discretization, the `diffeq_adjoint` just works. I know, not the nicest interface, but that'll always do, and I don't see that changing soon since writing an adjoint ODE on something where `length(p)` isn't the true length you want is hard!

For `diffeq_rd`, https://github.com/JuliaDiffEq/DiffEqFlux.jl/commit/daaac9aac9d93e92526ec06663a5a4dbe1af6593 fixes the type issue. So any ODE that is properly setup will work with it now! However, in your example code there was still an issue because you made a lot of assumptions that your parameters were going to be Float64 instead of TrackedReal{Float64} or TrackedArray. For more information on how to handle this, see the DiffEq FAQ. For all of your delta functions, just remove the type restrictions. Then in your delta buffer, you need to allow that to be an array of Tracked values as well. This example has some details: http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1 . It only took about 10-15 lines of changes to your PDE's MOL discretization to make that work, but let me know if you have any questions. So kudos and thanks for the report!
